let jsObject = [
  {
    levelType: "CATEGORY",
    code: "Street Lighting",
    catalogType: "PRODUCT",
    name: "Street Lighting",
    description: "Category code for Street Lighting",
    sourceLink: "http://lighttree.com/Street Lighting",
  },
  {
    levelType: "CATEGORY",
    code: "Pedestrian Lighting",
    catalogType: "PRODUCT",
    name: "Pedestrian Lighting",
    description: "Category code for Pedestrian Lighting",
    sourceLink: "http://lighttree.com/Pedestrian Lighting",
  },
  {
    levelType: "CATEGORY",
    code: "Traffic Signal Poles",
    catalogType: "PRODUCT",
    name: "Traffic Signal Poles",
    description: "Category code for Traffic Signal Poles",
    sourceLink: "http://lighttree.com/Traffic Signal Poles",
  },
  {
    levelType: "CATEGORY",
    code: "Controls",
    catalogType: "PRODUCT",
    name: "Controls",
    description: "Category code for Controls",
    sourceLink: "http://lighttree.com/Controls",
  },
  {
    levelType: "CATEGORY",
    code: "Downlights",
    catalogType: "PRODUCT",
    name: "Downlights",
    description: "Category code for Downlights",
    sourceLink: "http://lighttree.com/Downlights",
  },
  {
    levelType: "CATEGORY",
    code: "Retrofit Downlights",
    catalogType: "PRODUCT",
    name: "Retrofit Downlights",
    description: "Category code for Retrofit Downlights",
    sourceLink: "http://lighttree.com/Retrofit Downlights",
  },
  {
    levelType: "CATEGORY",
    code: "Ambient",
    catalogType: "PRODUCT",
    name: "Ambient",
    description: "Category code for Ambient",
    sourceLink: "http://lighttree.com/Ambient",
  },
  {
    levelType: "CATEGORY",
    code: "Bulbs",
    catalogType: "PRODUCT",
    name: "Bulbs",
    description: "Category code for Bulbs",
    sourceLink: "http://lighttree.com/Bulbs",
  },
  {
    levelType: "CATEGORY",
    code: "Controllers",
    catalogType: "PRODUCT",
    name: "Controllers",
    description: "Category code for Controllers",
    sourceLink: "http://lighttree.com/Controllers",
  },
  {
    levelType: "CATEGORY",
    code: "Enclosures",
    catalogType: "PRODUCT",
    name: "Enclosures",
    description: "Category code for Enclosures",
    sourceLink: "http://lighttree.com/Enclosures",
  },
  {
    levelType: "CATEGORY",
    code: "High Voltage Electrical",
    catalogType: "PRODUCT",
    name: "High Voltage Electrical",
    description: "Category code for High Voltage Electrical",
    sourceLink: "http://lighttree.com/High Voltage Electrical",
  },
  {
    levelType: "CATEGORY",
    code: "Lenses",
    catalogType: "PRODUCT",
    name: "Lenses",
    description: "Category code for Lenses",
    sourceLink: "http://lighttree.com/Lenses",
  },
  {
    levelType: "CATEGORY",
    code: "Luminaire",
    catalogType: "PRODUCT",
    name: "Luminaire",
    description: "Category code for Luminaire",
    sourceLink: "http://lighttree.com/Luminaire",
  },
  {
    levelType: "CATEGORY",
    code: "Mechanicals",
    catalogType: "PRODUCT",
    name: "Mechanicals",
    description: "Category code for Mechanicals",
    sourceLink: "http://lighttree.com/Mechanicals",
  },
  {
    levelType: "CATEGORY",
    code: "Primary Chassis",
    catalogType: "PRODUCT",
    name: "Primary Chassis",
    description: "Category code for Primary Chassis",
    sourceLink: "http://lighttree.com/Primary Chassis",
  },
  {
    levelType: "CATEGORY",
    code: "Primary Foundation",
    catalogType: "PRODUCT",
    name: "Primary Foundation",
    description: "Category code for Primary Foundation",
    sourceLink: "http://lighttree.com/Primary Foundation",
  },
  {
    levelType: "CATEGORY",
    code: "Secondary Chassis",
    catalogType: "PRODUCT",
    name: "Secondary Chassis",
    description: "Category code for Secondary Chassis",
    sourceLink: "http://lighttree.com/Secondary Chassis",
  },
  {
    levelType: "BRAND",
    code: "Public Sector",
    catalogType: "PRODUCT",
    name: "Public Sector",
    description: "Brand code for Public Sector",
    sourceLink: "http://lighttree.com/Public Sector",
  },
  {
    levelType: "BRAND",
    code: "Commercial",
    catalogType: "PRODUCT",
    name: "Commercial",
    description: "Brand code for Commercial",
    sourceLink: "http://lighttree.com/Commercial",
  },
  {
    levelType: "FAMILY",
    code: "Alliance",
    catalogType: "PRODUCT",
    name: "Alliance",
    description: "Family code for Alliance",
    sourceLink: "http://lighttree.com/Alliance",
  },
  {
    levelType: "FAMILY",
    code: "Helm",
    catalogType: "PRODUCT",
    name: "Helm",
    description: "Family code for Helm",
    sourceLink: "http://lighttree.com/Helm",
  },
  {
    levelType: "FAMILY",
    code: "Flatbush Avenue",
    catalogType: "PRODUCT",
    name: "Flatbush Avenue",
    description: "Family code for Flatbush Avenue",
    sourceLink: "http://lighttree.com/Flatbush Avenue",
  },
  {
    levelType: "FAMILY",
    code: "Bishops Crook",
    catalogType: "PRODUCT",
    name: "Bishops Crook",
    description: "Family code for Bishops Crook",
    sourceLink: "http://lighttree.com/Bishops Crook",
  },
  {
    levelType: "FAMILY",
    code: "City Light",
    catalogType: "PRODUCT",
    name: "City Light",
    description: "Family code for City Light",
    sourceLink: "http://lighttree.com/City Light",
  },
  {
    levelType: "FAMILY",
    code: "LED Type E",
    catalogType: "PRODUCT",
    name: "LED Type E",
    description: "Family code for LED Type E",
    sourceLink: "http://lighttree.com/LED Type E",
  },
  {
    levelType: "FAMILY",
    code: "All",
    catalogType: "PRODUCT",
    name: "All",
    description: "Family code for All",
    sourceLink: "http://lighttree.com/All",
  },
  {
    levelType: "FAMILY",
    code: "Cobra Head",
    catalogType: "PRODUCT",
    name: "Cobra Head",
    description: "Family code for Cobra Head",
    sourceLink: "http://lighttree.com/Cobra Head",
  },
  {
    levelType: "FAMILY",
    code: "Stad",
    catalogType: "PRODUCT",
    name: "Stad",
    description: "Family code for Stad",
    sourceLink: "http://lighttree.com/Stad",
  },
  {
    levelType: "FAMILY",
    code: "Fulton",
    catalogType: "PRODUCT",
    name: "Fulton",
    description: "Family code for Fulton",
    sourceLink: "http://lighttree.com/Fulton",
  },
  {
    levelType: "FAMILY",
    code: "Flushing Meadows",
    catalogType: "PRODUCT",
    name: "Flushing Meadows",
    description: "Family code for Flushing Meadows",
    sourceLink: "http://lighttree.com/Flushing Meadows",
  },
  {
    levelType: "FAMILY",
    code: "World’s Fair",
    catalogType: "PRODUCT",
    name: "World’s Fair",
    description: "Family code for World’s Fair",
    sourceLink: "http://lighttree.com/World’s Fair",
  },
  {
    levelType: "FAMILY",
    code: "Round Top Head",
    catalogType: "PRODUCT",
    name: "Round Top Head",
    description: "Family code for Round Top Head",
    sourceLink: "http://lighttree.com/Round Top Head",
  },
  {
    levelType: "FAMILY",
    code: "All",
    catalogType: "PRODUCT",
    name: "All",
    description: "Family code for All",
    sourceLink: "http://lighttree.com/All",
  },
  {
    levelType: "FAMILY",
    code: "Type M–2 Traffic Signal Pole",
    catalogType: "PRODUCT",
    name: "Type M–2 Traffic Signal Pole",
    description: "Family code for Type M–2 Traffic Signal Pole",
    sourceLink: "http://lighttree.com/Type M–2 Traffic Signal Pole",
  },
  {
    levelType: "FAMILY",
    code: "Alliance Traffic Signal Pole",
    catalogType: "PRODUCT",
    name: "Alliance Traffic Signal Pole",
    description: "Family code for Alliance Traffic Signal Pole",
    sourceLink: "http://lighttree.com/Alliance Traffic Signal Pole",
  },
  {
    levelType: "FAMILY",
    code: "All",
    catalogType: "PRODUCT",
    name: "All",
    description: "Family code for All",
    sourceLink: "http://lighttree.com/All",
  },
  {
    levelType: "FAMILY",
    code: "Ventura",
    catalogType: "PRODUCT",
    name: "Ventura",
    description: "Family code for Ventura",
    sourceLink: "http://lighttree.com/Ventura",
  },
  {
    levelType: "FAMILY",
    code: "Northridge ",
    catalogType: "PRODUCT",
    name: "Northridge ",
    description: "Family code for Northridge ",
    sourceLink: "http://lighttree.com/Northridge ",
  },
  {
    levelType: "FAMILY",
    code: "Miramar ",
    catalogType: "PRODUCT",
    name: "Miramar ",
    description: "Family code for Miramar ",
    sourceLink: "http://lighttree.com/Miramar ",
  },
  {
    levelType: "FAMILY",
    code: "Tulare",
    catalogType: "PRODUCT",
    name: "Tulare",
    description: "Family code for Tulare",
    sourceLink: "http://lighttree.com/Tulare",
  },
  {
    levelType: "FAMILY",
    code: "Alameda",
    catalogType: "PRODUCT",
    name: "Alameda",
    description: "Family code for Alameda",
    sourceLink: "http://lighttree.com/Alameda",
  },
  {
    levelType: "FAMILY",
    code: "Alpine",
    catalogType: "PRODUCT",
    name: "Alpine",
    description: "Family code for Alpine",
    sourceLink: "http://lighttree.com/Alpine",
  },
  {
    levelType: "FAMILY",
    code: "Imperial ",
    catalogType: "PRODUCT",
    name: "Imperial ",
    description: "Family code for Imperial ",
    sourceLink: "http://lighttree.com/Imperial ",
  },
  {
    levelType: "FAMILY",
    code: "Sunset ",
    catalogType: "PRODUCT",
    name: "Sunset ",
    description: "Family code for Sunset ",
    sourceLink: "http://lighttree.com/Sunset ",
  },
  {
    levelType: "FAMILY",
    code: "Riverside",
    catalogType: "PRODUCT",
    name: "Riverside",
    description: "Family code for Riverside",
    sourceLink: "http://lighttree.com/Riverside",
  },
  {
    levelType: "FAMILY",
    code: "Buccaneer ",
    catalogType: "PRODUCT",
    name: "Buccaneer ",
    description: "Family code for Buccaneer ",
    sourceLink: "http://lighttree.com/Buccaneer ",
  },
  {
    levelType: "FAMILY",
    code: "Santa Cruz ",
    catalogType: "PRODUCT",
    name: "Santa Cruz ",
    description: "Family code for Santa Cruz ",
    sourceLink: "http://lighttree.com/Santa Cruz ",
  },
  {
    levelType: "FAMILY",
    code: "Stinson ",
    catalogType: "PRODUCT",
    name: "Stinson ",
    description: "Family code for Stinson ",
    sourceLink: "http://lighttree.com/Stinson ",
  },
  {
    levelType: "LINE",
    code: "Rural",
    catalogType: "PRODUCT",
    name: "Rural",
    description: "Line code for Rural",
    sourceLink: "http://lighttree.com/Rural",
  },
  {
    levelType: "LINE",
    code: "City",
    catalogType: "PRODUCT",
    name: "City",
    description: "Line code for City",
    sourceLink: "http://lighttree.com/City",
  },
  {
    levelType: "LINE",
    code: "Special application",
    catalogType: "PRODUCT",
    name: "Special application",
    description: "Line code for Special application",
    sourceLink: "http://lighttree.com/Special application",
  },
  {
    levelType: "LINE",
    code: "Traffic",
    catalogType: "PRODUCT",
    name: "Traffic",
    description: "Line code for Traffic",
    sourceLink: "http://lighttree.com/Traffic",
  },
  {
    levelType: "CATEGORY",
    code: "Bulbs",
    catalogType: "ITEM",
    name: "Bulbs",
    description: "Category code for Bulbs",
    sourceLink: "http://lighttree.com/Bulbs",
  },
  {
    levelType: "CATEGORY",
    code: "Controllers",
    catalogType: "ITEM",
    name: "Controllers",
    description: "Category code for Controllers",
    sourceLink: "http://lighttree.com/Controllers",
  },
  {
    levelType: "CATEGORY",
    code: "Enclosures",
    catalogType: "ITEM",
    name: "Enclosures",
    description: "Category code for Enclosures",
    sourceLink: "http://lighttree.com/Enclosures",
  },
  {
    levelType: "CATEGORY",
    code: "High Voltage Electrical",
    catalogType: "ITEM",
    name: "High Voltage Electrical",
    description: "Category code for High Voltage Electrical",
    sourceLink: "http://lighttree.com/High Voltage Electrical",
  },
  {
    levelType: "CATEGORY",
    code: "Lenses",
    catalogType: "ITEM",
    name: "Lenses",
    description: "Category code for Lenses",
    sourceLink: "http://lighttree.com/Lenses",
  },
  {
    levelType: "CATEGORY",
    code: "Luminaire",
    catalogType: "ITEM",
    name: "Luminaire",
    description: "Category code for Luminaire",
    sourceLink: "http://lighttree.com/Luminaire",
  },
  {
    levelType: "CATEGORY",
    code: "Mechanicals",
    catalogType: "ITEM",
    name: "Mechanicals",
    description: "Category code for Mechanicals",
    sourceLink: "http://lighttree.com/Mechanicals",
  },
  {
    levelType: "CATEGORY",
    code: "Primary Chassis",
    catalogType: "ITEM",
    name: "Primary Chassis",
    description: "Category code for Primary Chassis",
    sourceLink: "http://lighttree.com/Primary Chassis",
  },
  {
    levelType: "CATEGORY",
    code: "Primary Foundation",
    catalogType: "ITEM",
    name: "Primary Foundation",
    description: "Category code for Primary Foundation",
    sourceLink: "http://lighttree.com/Primary Foundation",
  },
  {
    levelType: "CATEGORY",
    code: "Secondary Chassis",
    catalogType: "ITEM",
    name: "Secondary Chassis",
    description: "Category code for Secondary Chassis",
    sourceLink: "http://lighttree.com/Secondary Chassis",
  },
];

// console.log(Object.keys(jsObject[0]));
console.log(Object.values(jsObject[0]));
